version: '3'
services:
  client:
    build: frontend
    ports:
      - "94:80"
    networks:
      - nginx_proxy
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: backend
    ports:
      - "8084:8080"
    networks:
      - nginx_proxy
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true
    